import { SquadPlayer } from "@/services/sportsdb";

const P = (id: string, name: string, position: string): SquadPlayer => ({
  id,
  name,
  position,
});

export const LOCAL_ROSTERS: Record<string, SquadPlayer[]> = {
  "real-madrid": [
    P("rma-courtois", "Thibaut Courtois", "Goalkeeper"),
    P("rma-lunin", "Andriy Lunin", "Goalkeeper"),
    P("rma-carvajal", "Dani Carvajal", "Defender"),
    P("rma-vazquez", "Lucas Vazquez", "Defender"),
    P("rma-militao", "Eder Militao", "Defender"),
    P("rma-rudiger", "Antonio Rudiger", "Defender"),
    P("rma-alaba", "David Alaba", "Defender"),
    P("rma-mendy", "Ferland Mendy", "Defender"),
    P("rma-fran", "Fran Garcia", "Defender"),
    P("rma-camavinga", "Eduardo Camavinga", "Midfielder"),
    P("rma-tchouameni", "Aurelien Tchouameni", "Midfielder"),
    P("rma-valverde", "Federico Valverde", "Midfielder"),
    P("rma-bellingham", "Jude Bellingham", "Midfielder"),
    P("rma-guler", "Arda Guler", "Midfielder"),
    P("rma-ceballos", "Dani Ceballos", "Midfielder"),
    P("rma-vini", "Vinicius Junior", "Forward"),
    P("rma-rodrygo", "Rodrygo", "Forward"),
    P("rma-mbappe", "Kylian Mbappe", "Forward"),
    P("rma-endrick", "Endrick", "Forward"),
    P("rma-brahim", "Brahim Diaz", "Forward"),
  ],
  barcelona: [
    P("bar-joan", "Joan Garcia", "Goalkeeper"),
    P("bar-terstegen", "Marc-Andre ter Stegen", "Goalkeeper"),
    P("bar-inaki", "Inaki Pena", "Goalkeeper"),
    P("bar-kounde", "Jules Kounde", "Defender"),
    P("bar-araujo", "Ronald Araujo", "Defender"),
    P("bar-cubarsi", "Pau Cubarsi", "Defender"),
    P("bar-balde", "Alejandro Balde", "Defender"),
    P("bar-martinez", "Inigo Martinez", "Defender"),
    P("bar-eric", "Eric Garcia", "Defender"),
    P("bar-christensen", "Andreas Christensen", "Defender"),
    P("bar-fort", "Hector Fort", "Defender"),
    P("bar-gavi", "Gavi", "Midfielder"),
    P("bar-pedri", "Pedri", "Midfielder"),
    P("bar-dejong", "Frenkie de Jong", "Midfielder"),
    P("bar-olmo", "Dani Olmo", "Midfielder"),
    P("bar-fermin", "Fermin Lopez", "Midfielder"),
    P("bar-casado", "Marc Casado", "Midfielder"),
    P("bar-bernal", "Marc Bernal", "Midfielder"),
    P("bar-pau", "Pau Victor", "Forward"),
    P("bar-raphinha", "Raphinha", "Forward"),
    P("bar-yamal", "Lamine Yamal", "Forward"),
    P("bar-lewa", "Robert Lewandowski", "Forward"),
    P("bar-ferran", "Ferran Torres", "Forward"),
    P("bar-ansu", "Ansu Fati", "Forward"),
  ],
  bayern: [
    P("bay-neuer", "Manuel Neuer", "Goalkeeper"),
    P("bay-ulreich", "Sven Ulreich", "Goalkeeper"),
    P("bay-kimmich", "Joshua Kimmich", "Midfielder"),
    P("bay-upa", "Dayot Upamecano", "Defender"),
    P("bay-kim", "Kim Min-jae", "Defender"),
    P("bay-davies", "Alphonso Davies", "Defender"),
    P("bay-guerreiro", "Raphael Guerreiro", "Defender"),
    P("bay-boey", "Sacha Boey", "Defender"),
    P("bay-goretzka", "Leon Goretzka", "Midfielder"),
    P("bay-pavlovic", "Aleksandar Pavlovic", "Midfielder"),
    P("bay-laimer", "Konrad Laimer", "Midfielder"),
    P("bay-musiala", "Jamal Musiala", "Midfielder"),
    P("bay-coman", "Kingsley Coman", "Forward"),
    P("bay-sane", "Leroy Sane", "Forward"),
    P("bay-gnabry", "Serge Gnabry", "Forward"),
    P("bay-kane", "Harry Kane", "Forward"),
    P("bay-luisdiaz", "Luis Diaz", "Forward"),
    P("bay-olise", "Michael Olise", "Forward"),
    P("bay-palihnha", "Joao Palhinha", "Midfielder"),
  ],
  liverpool: [
    P("liv-alisson", "Alisson Becker", "Goalkeeper"),
    P("liv-kelleher", "Caoimhin Kelleher", "Goalkeeper"),
    P("liv-vvd", "Virgil van Dijk", "Defender"),
    P("liv-konate", "Ibrahima Konate", "Defender"),
    P("liv-robertson", "Andy Robertson", "Defender"),
    P("liv-trent", "Trent Alexander-Arnold", "Defender"),
    P("liv-gomez", "Joe Gomez", "Defender"),
    P("liv-mac", "Alexis Mac Allister", "Midfielder"),
    P("liv-szobo", "Dominik Szoboszlai", "Midfielder"),
    P("liv-jones", "Curtis Jones", "Midfielder"),
    P("liv-graven", "Ryan Gravenberch", "Midfielder"),
    P("liv-elliott", "Harvey Elliott", "Midfielder"),
    P("liv-salah", "Mohamed Salah", "Forward"),
    P("liv-gakpo", "Cody Gakpo", "Forward"),
    P("liv-nunez", "Darwin Nunez", "Forward"),
    P("liv-diaz", "Luis Diaz", "Forward"),
    P("liv-jota", "Diogo Jota", "Forward"),
  ],
  "man-city": [
    P("mci-ederson", "Ederson", "Goalkeeper"),
    P("mci-ortega", "Stefan Ortega", "Goalkeeper"),
    P("mci-dias", "Ruben Dias", "Defender"),
    P("mci-gvardiol", "Josko Gvardiol", "Defender"),
    P("mci-stones", "John Stones", "Defender"),
    P("mci-walker", "Kyle Walker", "Defender"),
    P("mci-ake", "Nathan Ake", "Defender"),
    P("mci-rodri", "Rodri", "Midfielder"),
    P("mci-kdb", "Kevin De Bruyne", "Midfielder"),
    P("mci-bernardo", "Bernardo Silva", "Midfielder"),
    P("mci-nunes", "Matheus Nunes", "Midfielder"),
    P("mci-foden", "Phil Foden", "Forward"),
    P("mci-doku", "Jeremy Doku", "Forward"),
    P("mci-grealish", "Jack Grealish", "Forward"),
    P("mci-haaland", "Erling Haaland", "Forward"),
    P("mci-alvarez", "Julian Alvarez", "Forward"),
    P("mci-bobb", "Oscar Bobb", "Forward"),
  ],
  arsenal: [
    P("ars-raya", "David Raya", "Goalkeeper"),
    P("ars-ramsdale", "Aaron Ramsdale", "Goalkeeper"),
    P("ars-neto", "Neto", "Goalkeeper"),
    P("ars-saliba", "William Saliba", "Defender"),
    P("ars-gabriel", "Gabriel Magalhaes", "Defender"),
    P("ars-white", "Ben White", "Defender"),
    P("ars-timber", "Jurrien Timber", "Defender"),
    P("ars-calafiori", "Riccardo Calafiori", "Defender"),
    P("ars-tierney", "Kieran Tierney", "Defender"),
    P("ars-zinchenko", "Oleksandr Zinchenko", "Defender"),
    P("ars-kiwior", "Jakub Kiwior", "Defender"),
    P("ars-rice", "Declan Rice", "Midfielder"),
    P("ars-odegaard", "Martin Odegaard", "Midfielder"),
    P("ars-merino", "Mikel Merino", "Midfielder"),
    P("ars-zubimendi", "Martin Zubimendi", "Midfielder"),
    P("ars-nwaneri", "Ethan Nwaneri", "Midfielder"),
    P("ars-lewis", "Myles Lewis-Skelly", "Midfielder"),
    P("ars-havertz", "Kai Havertz", "Forward"),
    P("ars-gyokeres", "Viktor Gyokeres", "Forward"),
    P("ars-saka", "Bukayo Saka", "Forward"),
    P("ars-martinelli", "Gabriel Martinelli", "Forward"),
    P("ars-jesus", "Gabriel Jesus", "Forward"),
    P("ars-sterling", "Raheem Sterling", "Forward"),
    P("ars-trossard", "Leandro Trossard", "Forward"),
  ],
  psg: [
    P("psg-safonov", "Matvey Safonov", "Goalkeeper"),
    P("psg-tenas", "Arnau Tenas", "Goalkeeper"),
    P("psg-hakimi", "Achraf Hakimi", "Defender"),
    P("psg-marquinhos", "Marquinhos", "Defender"),
    P("psg-hernandez", "Lucas Hernandez", "Defender"),
    P("psg-mendes", "Nuno Mendes", "Defender"),
    P("psg-ugarte", "Manuel Ugarte", "Midfielder"),
    P("psg-vitinha", "Vitinha", "Midfielder"),
    P("psg-zaire", "Warren Zaire-Emery", "Midfielder"),
    P("psg-fabian", "Fabian Ruiz", "Midfielder"),
    P("psg-lee", "Lee Kang-in", "Midfielder"),
    P("psg-dembele", "Ousmane Dembele", "Forward"),
    P("psg-barcola", "Bradley Barcola", "Forward"),
    P("psg-ramokolo", "Goncalo Ramos", "Forward"),
    P("psg-kvaratskhelia", "Khvicha Kvaratskhelia", "Forward"),
    P("psg-neves", "Joao Neves", "Midfielder"),
  ],
};

export function getLocalRoster(teamId: string): SquadPlayer[] {
  return LOCAL_ROSTERS[teamId] ?? [];
}
