const fs = require("fs");
const path = require("path");

const B = "https://crests.football-data.org/";

const lines = [
  `import { UCLTeam } from "./types";`,
  ``,
  `export const UCL_TEAMS: UCLTeam[] = [`,
  `  // England`,
  `  { id: "man-city", name: "Manchester City", shortName: "MCI", country: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", primaryColor: "#6CABDD", secondaryColor: "#1C2C5B", sportsDbName: "Manchester City", badgeUrl: "${B}65.svg" },`,
  `  { id: "arsenal", name: "Arsenal", shortName: "ARS", country: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", primaryColor: "#EF0107", secondaryColor: "#023474", sportsDbName: "Arsenal", badgeUrl: "${B}57.svg" },`,
  `  { id: "liverpool", name: "Liverpool", shortName: "LIV", country: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", primaryColor: "#C8102E", secondaryColor: "#00B2A9", sportsDbName: "Liverpool", badgeUrl: "${B}64.svg" },`,
  `  { id: "chelsea", name: "Chelsea", shortName: "CHE", country: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", primaryColor: "#034694", secondaryColor: "#DBA111", sportsDbName: "Chelsea", badgeUrl: "${B}61.svg" },`,
  `  { id: "aston-villa", name: "Aston Villa", shortName: "AVL", country: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", primaryColor: "#670E36", secondaryColor: "#95BFE5", sportsDbName: "Aston Villa", badgeUrl: "${B}58.svg" },`,
  `  { id: "man-utd", name: "Manchester United", shortName: "MUN", country: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", primaryColor: "#DA020E", secondaryColor: "#FFE500", sportsDbName: "Manchester United", badgeUrl: "${B}66.svg" },`,
  `  { id: "tottenham", name: "Tottenham Hotspur", shortName: "TOT", country: "Inglaterra", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", primaryColor: "#132257", secondaryColor: "#FFFFFF", sportsDbName: "Tottenham Hotspur", badgeUrl: "${B}73.svg" },`,
  `  // Spain`,
  `  { id: "real-madrid", name: "Real Madrid", shortName: "RMA", country: "España", flag: "🇪🇸", primaryColor: "#FEBE10", secondaryColor: "#00529F", sportsDbName: "Real Madrid", badgeUrl: "${B}86.svg" },`,
  `  { id: "barcelona", name: "FC Barcelona", shortName: "BAR", country: "España", flag: "🇪🇸", primaryColor: "#004D98", secondaryColor: "#A50044", sportsDbName: "FC Barcelona", badgeUrl: "${B}81.svg" },`,
  `  { id: "atletico", name: "Atlético Madrid", shortName: "ATM", country: "España", flag: "🇪🇸", primaryColor: "#CB3524", secondaryColor: "#272E61", sportsDbName: "Atletico Madrid", badgeUrl: "${B}78.svg" },`,
  `  { id: "girona", name: "Girona FC", shortName: "GIR", country: "España", flag: "🇪🇸", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "Girona", badgeUrl: "${B}298.svg" },`,
  `  { id: "villarreal", name: "Villarreal CF", shortName: "VIL", country: "España", flag: "🇪🇸", primaryColor: "#FFD700", secondaryColor: "#005F9E", sportsDbName: "Villarreal", badgeUrl: "${B}94.svg" },`,
  `  { id: "sevilla", name: "Sevilla FC", shortName: "SEV", country: "España", flag: "🇪🇸", primaryColor: "#FF1724", secondaryColor: "#FFFFFF", sportsDbName: "Sevilla", badgeUrl: "${B}559.svg" },`,
  `  // Germany`,
  `  { id: "bayern", name: "Bayern Munich", shortName: "BAY", country: "Alemania", flag: "🇩🇪", primaryColor: "#DC052D", secondaryColor: "#0066B2", sportsDbName: "Bayern Munich", badgeUrl: "${B}5.svg" },`,
  `  { id: "dortmund", name: "Borussia Dortmund", shortName: "BVB", country: "Alemania", flag: "🇩🇪", primaryColor: "#FDE100", secondaryColor: "#000000", sportsDbName: "Borussia Dortmund", badgeUrl: "${B}4.svg" },`,
  `  { id: "leipzig", name: "RB Leipzig", shortName: "RBL", country: "Alemania", flag: "🇩🇪", primaryColor: "#DD0741", secondaryColor: "#001E62", sportsDbName: "RB Leipzig", badgeUrl: "${B}721.svg" },`,
  `  { id: "leverkusen", name: "Bayer Leverkusen", shortName: "B04", country: "Alemania", flag: "🇩🇪", primaryColor: "#E32221", secondaryColor: "#000000", sportsDbName: "Bayer Leverkusen", badgeUrl: "${B}3.svg" },`,
  `  { id: "stuttgart", name: "VfB Stuttgart", shortName: "VFB", country: "Alemania", flag: "🇩🇪", primaryColor: "#E32219", secondaryColor: "#FFFFFF", sportsDbName: "VfB Stuttgart", badgeUrl: "${B}8.svg" },`,
  `  { id: "frankfurt", name: "Eintracht Frankfurt", shortName: "SGE", country: "Alemania", flag: "🇩🇪", primaryColor: "#E1000F", secondaryColor: "#000000", sportsDbName: "Eintracht Frankfurt", badgeUrl: "${B}9.svg" },`,
  `  // France`,
  `  { id: "psg", name: "Paris Saint-Germain", shortName: "PSG", country: "Francia", flag: "🇫🇷", primaryColor: "#004170", secondaryColor: "#DA291C", sportsDbName: "Paris Saint-Germain", badgeUrl: "${B}524.svg" },`,
  `  { id: "monaco", name: "AS Monaco", shortName: "MON", country: "Francia", flag: "🇲🇨", primaryColor: "#D4021D", secondaryColor: "#FFFFFF", sportsDbName: "Monaco", badgeUrl: "${B}1903.svg" },`,
  `  { id: "lille", name: "LOSC Lille", shortName: "LIL", country: "Francia", flag: "🇫🇷", primaryColor: "#CC092F", secondaryColor: "#0A1E5B", sportsDbName: "Lille", badgeUrl: "${B}521.svg" },`,
  `  { id: "brest", name: "Stade Brestois", shortName: "BRE", country: "Francia", flag: "🇫🇷", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "Stade Brest" },`,
  `  { id: "lyon", name: "Olympique Lyon", shortName: "OLY", country: "Francia", flag: "🇫🇷", primaryColor: "#0040A0", secondaryColor: "#CC0000", sportsDbName: "Lyon", badgeUrl: "${B}523.svg" },`,
  `  // Italy`,
  `  { id: "inter", name: "Inter Milan", shortName: "INT", country: "Italia", flag: "🇮🇹", primaryColor: "#010E80", secondaryColor: "#000000", sportsDbName: "Inter Milan", badgeUrl: "${B}108.svg" },`,
  `  { id: "ac-milan", name: "AC Milan", shortName: "ACM", country: "Italia", flag: "🇮🇹", primaryColor: "#FB090B", secondaryColor: "#000000", sportsDbName: "AC Milan", badgeUrl: "${B}98.svg" },`,
  `  { id: "juventus", name: "Juventus", shortName: "JUV", country: "Italia", flag: "🇮🇹", primaryColor: "#000000", secondaryColor: "#FFFFFF", sportsDbName: "Juventus", badgeUrl: "${B}109.svg" },`,
  `  { id: "atalanta", name: "Atalanta", shortName: "ATA", country: "Italia", flag: "🇮🇹", primaryColor: "#1E73BE", secondaryColor: "#000000", sportsDbName: "Atalanta", badgeUrl: "${B}102.svg" },`,
  `  { id: "bologna", name: "Bologna FC", shortName: "BOL", country: "Italia", flag: "🇮🇹", primaryColor: "#CC0000", secondaryColor: "#003E6D", sportsDbName: "Bologna", badgeUrl: "${B}103.svg" },`,
  `  { id: "napoli", name: "SSC Napoli", shortName: "NAP", country: "Italia", flag: "🇮🇹", primaryColor: "#12A0D7", secondaryColor: "#003DA5", sportsDbName: "Napoli", badgeUrl: "${B}113.svg" },`,
  `  { id: "lazio", name: "SS Lazio", shortName: "LAZ", country: "Italia", flag: "🇮🇹", primaryColor: "#87D8F7", secondaryColor: "#FFFFFF", sportsDbName: "Lazio", badgeUrl: "${B}110.svg" },`,
  `  { id: "roma", name: "AS Roma", shortName: "ROM", country: "Italia", flag: "🇮🇹", primaryColor: "#CC0000", secondaryColor: "#F5A623", sportsDbName: "AS Roma", badgeUrl: "${B}100.svg" },`,
  `  // Portugal`,
  `  { id: "benfica", name: "SL Benfica", shortName: "BEN", country: "Portugal", flag: "🇵🇹", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "SL Benfica", badgeUrl: "${B}498.svg" },`,
  `  { id: "porto", name: "FC Porto", shortName: "POR", country: "Portugal", flag: "🇵🇹", primaryColor: "#003F87", secondaryColor: "#FFFFFF", sportsDbName: "FC Porto", badgeUrl: "${B}496.svg" },`,
  `  { id: "sporting", name: "Sporting CP", shortName: "SCP", country: "Portugal", flag: "🇵🇹", primaryColor: "#009B3A", secondaryColor: "#FFD700", sportsDbName: "Sporting CP", badgeUrl: "${B}503.svg" },`,
  `  // Netherlands`,
  `  { id: "psv", name: "PSV Eindhoven", shortName: "PSV", country: "Países Bajos", flag: "🇳🇱", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "PSV Eindhoven", badgeUrl: "${B}674.svg" },`,
  `  { id: "feyenoord", name: "Feyenoord", shortName: "FEY", country: "Países Bajos", flag: "🇳🇱", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "Feyenoord", badgeUrl: "${B}675.svg" },`,
  `  { id: "ajax", name: "AFC Ajax", shortName: "AJX", country: "Países Bajos", flag: "🇳🇱", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "Ajax", badgeUrl: "${B}678.svg" },`,
  `  // Belgium`,
  `  { id: "club-brugge", name: "Club Brugge", shortName: "CLB", country: "Bélgica", flag: "🇧🇪", primaryColor: "#003DA5", secondaryColor: "#000000", sportsDbName: "Club Brugge", badgeUrl: "${B}813.svg" },`,
  `  // Scotland`,
  `  { id: "celtic", name: "Celtic FC", shortName: "CEL", country: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", primaryColor: "#006600", secondaryColor: "#FFFFFF", sportsDbName: "Celtic", badgeUrl: "${B}732.svg" },`,
  `  { id: "rangers", name: "Rangers FC", shortName: "RAN", country: "Escocia", flag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿", primaryColor: "#003D9B", secondaryColor: "#FFFFFF", sportsDbName: "", badgeUrl: "${B}733.svg" },`,
  `  // Austria`,
  `  { id: "salzburg", name: "FC Salzburg", shortName: "SAL", country: "Austria", flag: "🇦🇹", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "RB Salzburg", badgeUrl: "${B}1877.svg" },`,
  `  { id: "sturm-graz", name: "SK Sturm Graz", shortName: "STU", country: "Austria", flag: "🇦🇹", primaryColor: "#1A1A1A", secondaryColor: "#FFFFFF", sportsDbName: "Sturm Graz" },`,
  `  // Czech Republic`,
  `  { id: "sparta-prague", name: "Sparta Prague", shortName: "SPA", country: "Rep. Checa", flag: "🇨🇿", primaryColor: "#AA0000", secondaryColor: "#FFD700", sportsDbName: "AC Sparta Prague" },`,
  `  { id: "slavia-prague", name: "Slavia Prague", shortName: "SLA", country: "Rep. Checa", flag: "🇨🇿", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "SK Slavia Prague" },`,
  `  // Switzerland`,
  `  { id: "young-boys", name: "BSC Young Boys", shortName: "YB", country: "Suiza", flag: "🇨🇭", primaryColor: "#FDD00A", secondaryColor: "#000000", sportsDbName: "Young Boys", badgeUrl: "${B}1862.svg" },`,
  `  // Slovakia`,
  `  { id: "slovan", name: "Slovan Bratislava", shortName: "SLO", country: "Eslovaquia", flag: "🇸🇰", primaryColor: "#003F87", secondaryColor: "#FFFFFF", sportsDbName: "Slovan Bratislava" },`,
  `  // Croatia`,
  `  { id: "dinamo-zagreb", name: "Dinamo Zagreb", shortName: "DIN", country: "Croacia", flag: "🇭🇷", primaryColor: "#003F87", secondaryColor: "#FFFFFF", sportsDbName: "Dinamo Zagreb" },`,
  `  // Ukraine`,
  `  { id: "shakhtar", name: "Shakhtar Donetsk", shortName: "SHA", country: "Ucrania", flag: "🇺🇦", primaryColor: "#FF8000", secondaryColor: "#000000", sportsDbName: "Shakhtar Donetsk", badgeUrl: "${B}1887.svg" },`,
  `  { id: "dynamo-kyiv", name: "Dynamo Kyiv", shortName: "DYK", country: "Ucrania", flag: "🇺🇦", primaryColor: "#003DA5", secondaryColor: "#FFFFFF", sportsDbName: "Dynamo Kyiv" },`,
  `  // Serbia`,
  `  { id: "red-star", name: "Red Star Belgrade", shortName: "RSB", country: "Serbia", flag: "🇷🇸", primaryColor: "#CC0000", secondaryColor: "#FFFFFF", sportsDbName: "Red Star Belgrade" },`,
  `  // Turkey`,
  `  { id: "galatasaray", name: "Galatasaray", shortName: "GAL", country: "Turquía", flag: "🇹🇷", primaryColor: "#DD0706", secondaryColor: "#F7A800", sportsDbName: "Galatasaray", badgeUrl: "${B}1857.svg" },`,
  `  { id: "fenerbahce", name: "Fenerbahçe", shortName: "FEN", country: "Turquía", flag: "🇹🇷", primaryColor: "#003F87", secondaryColor: "#FFD700", sportsDbName: "Fenerbahce" },`,
  `  { id: "besiktas", name: "Beşiktaş JK", shortName: "BJK", country: "Turquía", flag: "🇹🇷", primaryColor: "#000000", secondaryColor: "#FFFFFF", sportsDbName: "Besiktas" },`,
  `  // Greece`,
  `  { id: "paok", name: "PAOK FC", shortName: "PAO", country: "Grecia", flag: "🇬🇷", primaryColor: "#1A1A1A", secondaryColor: "#FFFFFF", sportsDbName: "PAOK" },`,
  `];`,
  ``,
  `export function getTeamById(id: string): UCLTeam | undefined {`,
  `  return UCL_TEAMS.find((t) => t.id === id);`,
  `}`,
].join("\n");

const outPath = path.join(__dirname, "..", "constants", "teams.ts");
fs.writeFileSync(outPath, content, "utf8");
console.log("Written OK. Sample:", content.match(/badgeUrl: "[^"]+"/)?.[0]);
